### ISSUE TITLE
Bug in solution

### ISSUE THREAD

**Issue by zbeekman** [NVIDIA-OpenACC-Course/nvidia-openacc-course-sources#2]
See my comment here: https://github.com/NVIDIA-OpenACC-Course/nvidia-openacc-course-sources/commit/baa8e754d50f5ec8bef028fe60ab605714789dbf#commitcomment-17319069

basically `endy` fortran expression is wrong.

**Comment by zbeekman** [comment]
Here is the bad line: https://github.com/NVIDIA-OpenACC-Course/nvidia-openacc-course-sources/blob/master/labs/lab4.pipelining/f90/task1/main_solution.F90#L18

**Comment by jefflarkin** [comment]
Fixed in https://github.com/NVIDIA-OpenACC-Course/nvidia-openacc-course-sources/commit/204c6f7122321f8535d94087abfd72734e3d90ba, thanks.
