### ISSUE TITLE
seg fault in lab2 f90

### ISSUE THREAD

**Issue by pkestene** [NVIDIA-OpenACC-Course/nvidia-openacc-course-sources#4]
Hello,

There is a seg fault when running 
lab2/f90/solution.kernels/cg

Seg fault appears in subroutine allocate_3d_poisson_matrix

actually the problem is due to the fact that parameter "n" is modified (line 58 of matrix.F90), whereas in main.F90 n is declared as
integer, parameter   :: n

Just need to change variable name to avoid this problem.
(NB: problem discovered while compiling this lab on a Power8 system).

**Comment by jefflarkin** [comment]
Good catch, thanks for reporting. I'm in the process of updating these sources and will make this fix. Thanks.

**Comment by jefflarkin** [comment]
Resolved in commit 5aaaf95e7c1b97d0de25371975f5b90bd82adfcd. Thanks for reporting this.
